<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quote - {{ $contract->customer_name }}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-white text-gray-800 p-10">

    <div class="max-w-3xl mx-auto">
        <!-- Header -->
        <div class="text-center mb-10">
            <h1 class="text-4xl font-bold text-blue-600">SolarVolt</h1>
            <h2 class="text-2xl mt-2 font-semibold">Quote Document</h2>
            <p class="text-sm text-gray-500 mt-1">Date: {{ now()->format('d M Y') }}</p>
        </div>

        <!-- Customer Info -->
        <div class="mb-8">
            <h3 class="text-xl font-semibold mb-2 border-b pb-1">Customer Information</h3>
            <p><span class="font-medium">Customer:</span> {{ $contract->customer_name }}</p>
            <p><span class="font-medium">Site Address:</span> {{ $contract->site_address }}</p>
        </div>

        <!-- Quote Info -->
        <div class="mb-8">
            <h3 class="text-xl font-semibold mb-2 border-b pb-1">Quote Details</h3>
            <p><span class="font-medium">Type:</span> {{ ucfirst($quote->type) }} Quote</p>
            <p><span class="font-medium">Amount:</span> ₹{{ number_format($quote->amount, 2) }}</p>
            @if($quote->details)
                <p><span class="font-medium">Details:</span> {{ $quote->details }}</p>
            @endif
            <p><span class="font-medium">Generated By:</span> Admin #{{ $quote->created_by }}</p>
        </div>

        <!-- Product Info -->
        <div class="mb-8">
            <h3 class="text-xl font-semibold mb-2 border-b pb-1">Associated Products</h3>
            @if(!empty($contract->product_ids))
                <ul class="list-disc pl-6 text-gray-700">
                    @foreach($contract->product_ids as $productId)
                        <li>Product ID: {{ $productId }}</li>
                    @endforeach
                </ul>
            @else
                <p>No products linked to this contract.</p>
            @endif
        </div>

        <!-- Footer -->
        <div class="text-center border-t pt-4 mt-10 text-sm text-gray-600">
            <p>Thank you for choosing <span class="font-semibold text-blue-600">SolarVolt</span>.</p>
            <p class="mt-1">Generated on {{ now()->format('d M Y, H:i') }}</p>
        </div>
    </div>

</body>
</html>
